Repository DevExpress/devextreme-quill, pull requests merged in 2022-12, with the labels that each got.

#73 Quill 1.5: try to fix CI
  .github/actions/quill/steps/functional-tests/action.yml
  package-lock.json
  package.json
  test/functional/epic.js
Labels: 1_5, CI

#70 T1113606: Fix table attributors keyNames collision.
  attributors/attributor.js
  attributors/decorators.js
  attributors/element_attributor.js
  attributors/element_class.js
  attributors/element_style.js
  attributors/style_attributor.js
  attributors/utils.js
  blots/block.js
  formats/table/attributors/cell.js
  formats/table/attributors/cell_config.js
  formats/table/attributors/prepare_attributor.js
  formats/table/attributors/prepare_style_attributor.js
  formats/table/attributors/table.js
  formats/table/attributors/table_config.js
  modules/table/utils/prepare_attr_matcher.js
  package-lock.json
  package.json
  parchment/override.js
  quill.js
  test/unit/blots/inline.js
  test/unit/modules/table_main.js
Labels: bug, 1_6

#74 Fix the incorrect behavior of the table's row styles
  formats/table/attributors/cell_config.js
  modules/clipboard.js
  modules/table/index.js
  modules/table/lite.js
  modules/table/utils/prepare_attr_matcher.js
  package-lock.json
  package.json
  test/unit/modules/table_lite.js
  test/unit/modules/table_main.js
Labels: bug, 1_5

#75 Fix the incorrect behavior of the table's row styles
  formats/table/attributors/cell_config.js
  modules/clipboard.js
  modules/table/index.js
  modules/table/lite.js
  modules/table/utils/prepare_attr_matcher.js
  package-lock.json
  package.json
  test/unit/modules/table_lite.js
  test/unit/modules/table_main.js
Labels: bug, 1_6

#78 Fix HtmlEditor testcafe CI checks after the devextreme repo update.
  .github/actions/html-editor/steps/build/action.yml
Labels: 1_6, CI

#79 Fix HtmlEditor testcafe CI checks after the devextreme repo update.
  .github/actions/html-editor/steps/build/action.yml
Labels: 1_5, CI

#76 Fix typo in version. 1.15.20 -> 1.5.20
  package-lock.json
  package.json
Labels: 1_5

#80 Add publish to npm action
  .github/workflows/publish.yml
Labels: 1_6, CI
