Repository DevExpress/devextreme-quill, pull requests merged in 2025-10, with the labels that each got.

#162 Cherry-pick SVG sanitizing to 1_6 and bump to 1.6.5
  .github/actions/html-editor/common/get-artifact/action.yml
  .github/actions/html-editor/common/prepare/action.yml
  .github/actions/html-editor/steps/build/action.yml
  .github/actions/html-editor/steps/testcafe-tests/action.yml
  .github/actions/quill/common/get-artifact/action.yml
  .github/actions/quill/steps/build-package/action.yml
  .github/actions/quill/steps/build/action.yml
  .github/workflows/html-editor-checks.yml
  .github/workflows/publish.yml
  modules/uploader.js
  package-lock.json
  package.json
  test/unit.js
  test/unit/modules/uploader.js
  test/unit/utils/sanitize_svg.js
  utils/sanitize_svg.js
Labels: 1_6

#164 Fix case-sensitive behavior with attributes when sanitizing SVG
  test/unit/utils/sanitize_svg.js
  utils/sanitize_svg.js
Labels: bug

#165 Fix case-sensitive behavior with attributes when sanitizing SVG (1.6)
  test/unit/utils/sanitize_svg.js
  utils/sanitize_svg.js
Labels: 1_6

#166 Bump version to 1.7.6
  package-lock.json
  package.json
Labels: 1_7
